### ISSUE TITLE
An question about the transparent objects?

### ISSUE THREAD

**Issue by HeKejing** [lvjiahui/DRT#3]
Hi, Jiahui. Is the transparent objects with the single refractive index manufactured by your lab? Because the transparent objects with single refractive index in market are rarely found (Mainly surface is covered with a layer of glaze).

**Comment by lvjiahui** [comment]
Hi, HeKejing.
We bought them from Taobao.

**Comment by HeKejing** [comment]
Can you share some links for us to buy these things? Thanks very much.

**Comment by lvjiahui** [comment]
Hope it can help you.
![tb_image_share_1614761044146](https://user-images.githubusercontent.com/28430051/109778418-c253fc80-7c3f-11eb-8613-39ac770aec45.jpg)

**Comment by HeKejing** [comment]
Appreciate for your information.
